### ISSUE TITLE
runv kill dosen't clean up properly if have process other than init in container

### ISSUE THREAD

**Issue by YaoZengzeng** [hyperhq/runv#373] opened 2016-10-24 04:37 UTC
First I start a container and exec in it

root@monster-Z:/home/monster/TEST/runv/container# runv start test
/ # ps
PID   USER     TIME   COMMAND
    1 root       0:00 /init
    3 root       0:00 sh
    4 root       0:00 ping 127.0.0.1
    5 root       0:00 ps

Then after I kill it , we can find it still alive through `runv list`

root@monster-Z:/home/monster/TEST/runv/container# runv list
ID          PID         STATUS      BUNDLE                              CREATED
test        6719        running     /home/monster/TEST/runv/container   2016-10-24T12:31:05.333658596+08:00
root@monster-Z:/home/monster/TEST/runv/container# runv kill test KILL
root@monster-Z:/home/monster/TEST/runv/container# runv list
ID          PID         STATUS      BUNDLE                              CREATED
test        6719        running     /home/monster/TEST/runv/container   2016-10-24T12:31:05.333658596+08:00

**Comment by YaoZengzeng** [comment] 2016-10-26 02:19
It seems when runv is connected with docker-containerd, there is no such problem.

**Comment by laijs** [comment] 2017-03-09 03:58
I can't reproduce the problem as this issues said.

Other processes will be killed in hyperstart(https://github.com/hyperhq/hyperstart/pull/96), the runv will receive the finished events, and cleanup the processes.

**Comment by gnawux** [comment] 2017-05-16 09:19
close this issue since it does not appear in current head.

**Closed by gnawux** 2017-05-16 09:19 UTC
